# -*- coding: utf-8 -*-
"""zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOvN_0jTsgg4FYrze7mPY-R-2A5wtenP
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

orders = pd.read_csv("Orders.csv")
orders.head()

customers = pd.read_csv("Customers.csv")
customers.head()

restaurants = pd.read_csv("Restaurants.csv")
restaurants.head()

orders.info()

orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])
orders.info()

orders

orders["Month"] = orders["Order_Date"].dt.strftime("%B")
orders

plt.figure(figsize=(6,3))
sns.countplot(x="Month", data=orders,hue="Month")
plt.xticks(rotation=25)
plt.show()

orders["Hour"] = orders["Order_Date"].dt.strftime("%H")
orders["Hour"]=orders["Hour"].astype(int)
orders.info()
orders.sort_values(by="Hour")
sns.lineplot(x="Hour", y="Order_ID", data=orders)
plt.show()

orders["Hour"] = orders["Order_Date"].dt.strftime("%H")
orders["Hour"] = orders["Hour"].astype("int")
orders = orders.sort_values(by = "Hour")
sns.lineplot(x = "Hour", y = "Order_ID", data = orders,estimator=sum)
plt.show()

orders["Hour"] = orders["Order_Date"].dt.strftime("%H")
orders["Hour"]=orders["Hour"].astype(int)
orders.info()
orders.sort_values(by="Hour")
sns.lineplot(x="Hour", y="Total_Amount", data=orders)
plt.show()

orders["Hour"] = orders["Order_Date"].dt.strftime("%H")
orders["Hour"]=orders["Hour"].astype(int)
orders.info()
orders.sort_values(by="Hour")
sns.lineplot(x="Hour", y="Total_Amount", data=orders,estimator=sum)
plt.show()

df=pd.merge(left=orders,right=customers,on="Customer_ID",how="inner")
df.head()

plt.figure(figsize=(8,4))
sns.countplot(x="Customer_Location",data=df, hue="Dish_Name",edgecolor="black")
plt.xticks(rotation=25)
plt.legend(bbox_to_anchor=(1,1))
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x="Customer_Location",data=df, hue="Order_Status",palette="rainbow",edgecolor="black")
plt.legend(bbox_to_anchor=(1,1))
plt.xticks(rotation=25)
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x="Customer_Location",data=df, hue="Customer_Age_Group",palette="viridis",edgecolor="black")
plt.legend(bbox_to_anchor=(1,1))
plt.xticks(rotation=25)
plt.show()

restaurants

